# Generated by Django 3.2.9 on 2024-03-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_id', models.IntegerField(default=0)),
                ('access_level', models.CharField(max_length=200)),
                ('menu', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('roles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.roles')),
            ],
        ),
    ]
