# Generated by Django 3.2.9 on 2024-03-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.roles'),
        ),
    ]
